name: Playwright Tests

on:
  push:
    branches: [main, feat-docker-playwright]
  pull_request:
    branches: [main]

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test tests/registration.spec.js --project=chromium
